ISO_REGION_LANGUAGES = {
    # Middle East / West Asia
    "palestine": ["ar", "he", "en"],
    "kurdistan": ["ku", "ar", "tr", "fa"],
    "gaza": ["ar", "he"],
    "west bank": ["ar", "he"],
    "hezbollah": ["ar", "fa"],
    "yemen": ["ar"],
    "levant": ["ar", "en", "he"],
    # South Asia
    "balochistan": ["ur", "fa"],
    "kashmir": ["ur", "hi", "en"],
    "punjab": ["pa", "en", "hi", "ur"],
    "northeast india": ["en", "as", "bn"],
    "sri lanka": ["si", "ta", "en"],
    "sindh": ["sd", "ur"],
    "bangladesh": ["bn", "en"],
    # Central & East Asia
    "tibet": ["zh"],
    "xinjiang": ["zh"],
    "hong kong": ["zh", "en"],
    "taiwan": ["zh", "en"],
    "mongolia": ["mn"],
    # Africa
    "somaliland": ["so", "en", "ar"],
    "darfur": ["ar", "en"],
    "sahara": ["ar", "fr"],
    "cabinda": ["pt"],
    "eritrea": ["ar"],
    "tigray": ["am"],
    # Europe
    "catalonia": ["ca", "es", "en"],
    "basque country": ["eu", "es", "fr"],
    "kosovo": ["sq", "sr"],
    "scotland": ["en"],
    "wales": ["cy", "en"],
    "ireland": ["en", "ga"],
    "crimea": ["uk", "ru"],
    "transnistria": ["ro", "ru", "uk"],
    "nagorno": ["hy", "az"],
    "karabakh": ["hy", "az"],
    # Americas
    "quebec": ["fr", "en"],
    "greenland": ["da"],
    "amazon": ["pt", "es"],
    "chiapas": ["es"],
    # Oceania / Pacific
    "papua": ["id"],
    "caledonia": ["fr"],
    "bougainville": ["en"],
    # Russia / Post-Soviet
    "chechnya": ["ru"],
    "dagestan": ["ru"],
    "donbas": ["uk", "ru"],
    "abkhazia": ["ru", "ka"],
    "ossetia": ["ru", "ka"],
    "kaliningrad": ["ru", "de", "pl"],
    # Pan-Identity / Civilization Zones
    "turk": ["tr", "az", "tk", "kk", "uz"],
    "arab": ["ar"],
    "persian": ["fa"],
    "latin": ["es", "pt"],
    "francophone": ["fr"],
    "anglo": ["en"],
    "slav": ["ru", "uk", "pl", "sr"],
    "sino": ["zh"],
    "kurd": ["ku"],
    "tamil": ["ta"],
    "hindi": ["hi"],
    "jewish": ["he", "en"],
    "islamic": ["ar", "fa", "ur"],
    "buddhist": ["zh", "th", "si"],
    "uralic": ["fi", "et", "hu"],
    # Stateless Nations
    "kurds": ["ku", "tr", "ar", "fa"],
    "rohingya": ["my"],
    "uyghurs": ["zh"],
    "tamils": ["ta", "en"],
    "tibetans": ["bo", "en"],
}
